apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.cleanupJobs.rbac.serviceAccount.automountServiceAccountToken.enabled }}
metadata:
  name: {{ template "kyverno.name" . }}-cleanup-jobs
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.labels.merge" (list (include "kyverno.labels.common" .) (include "kyverno.matchLabels.common" .)) | nindent 4 }}
