{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-ironbank
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kyverno.labels" . | nindent 4 }}
    app: kyverno
spec:
  podSelector: {}
  egress:
    - to:
      - ports: {{- range .Values.registries.ports | default 443 }}
          # ONLY Block requests to cloud metadata IP
          except:
          - 169.254.169.254/32
          {{- end }}
  policyTypes:
    - Egress
{{- end }}