{{- if and .Values.networkPolicies.enabled (.Values.networkPolicies.externalRegistries).allowEgress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-container-registry
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kyverno.labels.merge" (list (include "kyverno.labels.common" .) (include "kyverno.admission-controller.matchLabels" .)) | nindent 4 }}
    app: kyverno
spec:
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
          - 169.254.169.254/32
      ports:
        {{- if .Values.networkPolicies.externalRegistries.ports }}
        {{- toYaml .Values.networkPolicies.externalRegistries.ports | nindent 6 }}
        {{- else }}
        - protocol: TCP
          port: 443
        {{- end }}
  podSelector: 
    matchLabels: {{- include "kyverno.labels.merge" (list (include "kyverno.labels.common" .) (include "kyverno.admission-controller.matchLabels" .)) | nindent 8 }}
  policyTypes:
    - Egress
{{- end }}
