{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-ironbank
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kyverno.labels" . | nindent 4 }}
    app: kyverno
spec:
  podSelector: {}
  egress:
    - to:
      - ipBlock:
          #Allow egress to registry
          cidr: {{ .Values.registries.cidr }}
  policyTypes:
    - Egress
{{- end }}