{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-ironbank
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kyverno.labels" . | nindent 4 }}
    app: kyverno
spec:
  egress:
    - to:
      - namespaceSelector: 
          matchLabels:
            app.kubernetes.io/name: kyverno
      ports:
      {{- range $key, $value := $.Values.registries.ports }}
          {{ $key }}: 
            {{ toYaml $value }}
      {{- end }}
          # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
  podSelector: 
    matchLabels: {{ include "kyverno.labels" . | nindent 8 }}
  policyTypes:
  - Egress
{{- end }}