{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-ironbank
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kyverno.labels" . | nindent 4 }}
    app: kyverno
spec:
  podSelector: {}
  egress:
    - to:
      - ipBlock:
          cidr:
          #Allow egress to ironbank
          - 15.205.173.153/32
          {{- end }}
  policyTypes:
    - Egress
{{- end }}
