{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: "{{ .Release.Namespace }}"
  labels: {{ include "kyverno.labels" . | nindent 4 }}
    app: kyverno
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress: []
{{- end }}
