{{- if and .Values.networkPolicies.enabled .Values.upstream.admissionController.serviceMonitor.enabled}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-metric-scraping
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                app.kubernetes.io/name: monitoring
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: {{ .Values.upstream.admissionController.metricsService.port }}
          protocol: TCP
  podSelector:
      matchLabels: 
      {{- $version := "" | regexReplaceAll "-bb.*" .Chart.Version }}
      {{- $labels := (include "kyverno.labels.merge" (list (include "kyverno.labels.common" .) (include "kyverno.matchLabels.common" .)) | fromYaml) }}
      {{- $_ := set $labels "app.kubernetes.io/version" $version }}
      {{- $_ := set $labels "helm.sh/chart" (printf "upstream-%s" $version) }}
      {{- toYaml $labels | nindent 8 }}
  policyTypes:
    - Ingress
{{- end }}
