{{- if and .Values.networkPolicies.enabled .Values.kyverno.admissionController.serviceMonitor.enabled}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-metric-scraping
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                app.kubernetes.io/name: monitoring
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: {{ .Values.kyverno.admissionController.metricsService.port }}
          protocol: TCP
  podSelector:
      matchLabels: {{- include "kyverno.labels.merge" (list (include "kyverno.labels.common" .) (include "kyverno.matchLabels.common" .)) | nindent 8 }}
  policyTypes:
    - Ingress
{{- end }}
